### ISSUE TITLE
Cannot update from Version 1.1.27 dev build 2 to 1.1.27 ?

### ISSUE THREAD

**Issue by fabio42170** [gruz/MVC-Override#3]
Hello,
It's been a few weeks Joomla keeps reminding me to update mvc from Version 1.1.27 dev build 2 to version 1.1.27. And this, in spite of my updating it and having a successful message ...
![image](https://user-images.githubusercontent.com/41090804/73384136-ef124380-42ca-11ea-890d-692ec91de5f4.png)
How come ? Any idea ?
After updating, a few hours later , I've got this:
![image](https://user-images.githubusercontent.com/41090804/73468864-c26f3200-4385-11ea-85e5-a1e4547a2895.png)

Fabio

**Comment by gruz** [comment]
Hi. Please, try updating to the latest version. Should fix.
